"""add the detailed_qa to onboarding table

Revision ID: 1a5a4ee6226c
Revises: 0bfd096fef87
Create Date: 2024-08-22 16:07:48.544982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5a4ee6226c'
down_revision: Union[str, None] = '0bfd096fef87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('detailed_qa', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'onboarding', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'onboarding', type_='unique')
    op.drop_column('onboarding', 'detailed_qa')
    # ### end Alembic commands ###
