"""Update Onboarding table field

Revision ID: bca8b8d781c8
Revises: 7b22e29369af
Create Date: 2024-08-21 13:34:33.757595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca8b8d781c8'
down_revision: Union[str, None] = '7b22e29369af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('primary_personality', sa.String(), nullable=True))
    op.add_column('onboarding', sa.Column('specific_personality', sa.JSON(), nullable=True))
    op.add_column('onboarding', sa.Column('feedback', sa.Text(), nullable=True))
    op.add_column('onboarding', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('onboarding', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('onboarding', 'detailed_profile_info')
    op.drop_column('onboarding', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('onboarding', sa.Column('detailed_profile_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('onboarding', 'updated_at')
    op.drop_column('onboarding', 'created_at')
    op.drop_column('onboarding', 'feedback')
    op.drop_column('onboarding', 'specific_personality')
    op.drop_column('onboarding', 'primary_personality')
    # ### end Alembic commands ###
